services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        user: ${APP_USER:-laravel}
        uid: ${APP_UID:-1000}
    container_name: laravel-app-prod
    restart: unless-stopped
    working_dir: /var/www
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      # Use external DB (provide via .env or environment)
      DB_CONNECTION: ${DB_CONNECTION:-mysql}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-3306}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - prod-network

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx-prod
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/var/www/public:ro
    networks:
      - prod-network

networks:
  prod-network:
    driver: bridge
