services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        user: ${APP_USER:-laravel}
        uid: ${APP_UID:-1000}
    container_name: laravel-app-prod
    restart: unless-stopped
    working_dir: /var/www
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      # Use external DB (provide via .env or environment)
      DB_CONNECTION: ${DB_CONNECTION:-mysql}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-3306}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - prod-network

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx-prod
    restart: unless-stopped
    depends_on:
      - app
    environment:
      SERVER_NAME: ${SERVER_NAME}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/prod-https.conf.template:/etc/nginx/conf.d/default.conf.template:ro
      - ./public:/var/www/public:ro
      - letsencrypt:/etc/letsencrypt
      - certbot-web:/var/www/certbot
    command: >-
      /bin/sh -lc '
      if [ -z "$SERVER_NAME" ]; then echo "SERVER_NAME não definido" >&2; exit 1; fi;
      if [ -f "/etc/letsencrypt/live/$SERVER_NAME/fullchain.pem" ] && [ -f "/etc/letsencrypt/live/$SERVER_NAME/privkey.pem" ]; then ENABLE_SSL=1; else ENABLE_SSL=0; fi;
      echo "[nginx] SERVER_NAME=$SERVER_NAME ENABLE_SSL=$ENABLE_SSL";
      if [ "$ENABLE_SSL" = "1" ]; then
        export ENABLE_SSL;
        envsubst '$$SERVER_NAME $$ENABLE_SSL' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf;
      else
        # Strip SSL block between #BEGIN_SSL and #END_SSL
        awk '/#BEGIN_SSL/{flag=1; next} /#END_SSL/{flag=0; next} !flag {print}' /etc/nginx/conf.d/default.conf.template | ENABLE_SSL=0 envsubst '$$SERVER_NAME $$ENABLE_SSL' > /etc/nginx/conf.d/default.conf;
      fi;
      nginx -t && exec nginx -g "daemon off;"'
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - prod-network

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot-web:/var/www/certbot
    entrypoint: "/bin/sh -c"
    command: "certbot --version" # placeholder; use 'make certbot-init' and 'make ssl-renew'
    networks:
      - prod-network

networks:
  prod-network:
    driver: bridge

volumes:
  letsencrypt:
  certbot-web:
