services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        user: ${APP_USER:-laravel}
        uid: ${APP_UID:-1000}
    container_name: laravel-app-prod
    restart: unless-stopped
    working_dir: /var/www
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      DB_CONNECTION: ${DB_CONNECTION:-mysql}
      DB_HOST: ${DB_HOST:-database}
      DB_PORT: ${DB_PORT:-3306}
      DB_DATABASE: ${DB_DATABASE:-laravel}
      DB_USERNAME: ${DB_USERNAME:-laravel}
      DB_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - ./:/var/www
    networks:
      - prod-network

  nginx:
    image: nginx:1.25-alpine
    container_name: laravel-nginx-prod
    restart: unless-stopped
    depends_on:
      - app
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME:-localhost}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.docker/nginx/conf.d/default.conf:/etc/nginx/templates/default.conf.template
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/var/www/public:ro
      - certbot_conf:/etc/letsencrypt:ro
      - certbot_www:/var/www/certbot:ro
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://127.0.0.1/health || exit 1" ]
    networks:
      - prod-network

networks:
  prod-network:
    driver: bridge

volumes:
  certbot_conf:
  certbot_www:
  db_data: